name: "ShellCheck"

on:
  pull_request:
  push:
    branches:
      - '[0-9]+.[0-9]+.x'
      - 'refs/pull/*'
    tags:

jobs:
  shellcheck:
    name: "ShellCheck"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7

      - name: "Run ShellCheck"
        uses: "reviewdog/action-shellcheck@0722bbdb0d47f04c1b53b8734d2422ac63a45ec6" # v1
        with:
          fail_on_error: true
